version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped